### ISSUE TITLE
Enrollment and evaluation

### ISSUE THREAD

**Issue by hafsabukhary** [ArvinSiChuan/speaker-rec-keras#3]
Hi ,

You have done really great work. Please let me know if you are planning to complete evaluation and enrollment part.

**Comment by ArvinSiChuan** [comment]
Hi,@hafsabukhary   
There will be Enrollment and Evaluation, but the schedule is not sure now. I have been there fining training with the  VoxCeleb dataset but there is only a limited GPU and a slow disk. I think it would be better to fine this part well and then continue. Only if training works well, Enrollment and Evaluation will be useful there, isn't it?

**Comment by hafsabukhary** [comment]
Yes you are right :)
